# From https://orchid00.github.io/actions_sandbox/websites-using-pkgdown-bookdown-and-blogdown.html#deploy-bookdown
on:
  push:
     branches:
       - main

name: renderbook

jobs:
  bookdown:
    name: Render & Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install rmarkdown
        run: Rscript -e 'install.packages(c("rmarkdown","bookdown"))'
      - name: Check if book is present
        id: check_book
        uses: andstor/file-existence-action@v1
        with:
          files: "index.Rmd"
      - name: Generate book
        if: steps.check_book.outputs.files_exists == 'false'
        run: Rscript -e 'bookdown::create_gitbook(".")'
      - name: Render Book
        run: Rscript -e 'bookdown::render_book("index.Rmd")'
      - name: Deploy to GitHub Pages
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          build_dir: _book/ # "_site/" by default
          email: ${{ secrets.EMAIL }}  # must be a verified email
